//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBusTicket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int aId { get; set; }
        public string aUsername { get; set; }
        public string aPassword { get; set; }
        public string aName { get; set; }
        public System.DateTime aBirthday { get; set; }
        public string aEmail { get; set; }
        public string aPhone { get; set; }
    }
}
