//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBusTicket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlockTime1
    {
        public int btId { get; set; }
        public int StartPlace { get; set; }
        public int Destination { get; set; }
        public System.DateTime StartTime { get; set; }
        public float Price { get; set; }
    }
}
