//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBusTicket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlockTime
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BlockTime()
        {
            this.BusSchedules = new HashSet<BusSchedule>();
            this.Routes = new HashSet<Route>();
        }
    
        public int btId { get; set; }
        public int StartPlace { get; set; }
        public int Destination { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public double btPrice { get; set; }
    
        public virtual Counter Counter { get; set; }
        public virtual Counter Counter1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BusSchedule> BusSchedules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Route> Routes { get; set; }
    }
}
