//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBusTicket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingDetail
    {
        public int bkdId { get; set; }
        public int bkId { get; set; }
        public int rId { get; set; }
        public int cId { get; set; }
        public int sId { get; set; }
        public byte cAge { get; set; }
        public double rPrice { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Route Route { get; set; }
        public virtual Seat Seat { get; set; }
    }
}
