//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBusTicket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Route()
        {
            this.BookingDetails = new HashSet<BookingDetail>();
            this.RouteDetails = new HashSet<RouteDetail>();
        }
    
        public int rId { get; set; }
        public int bId { get; set; }
        public int btId { get; set; }
        public double rPrice { get; set; }
        public System.DateTime date { get; set; }

        //public Route(int r,int b,int bt,double p,DateTime d)
        //{
        //    this.rId = r;
        //    this.bId = b;
        //    this.btId = bt;
        //    this.rPrice = p;
        //    this.date = d;
        //}
        public virtual BlockTime BlockTime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingDetail> BookingDetails { get; set; }
        public virtual Bus Bus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RouteDetail> RouteDetails { get; set; }
    }
}
