//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBusTicket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RouteDetail
    {
        public int rdId { get; set; }
        public int rId { get; set; }
        public int sId { get; set; }
        public byte avaibility { get; set; }
    
        public virtual Route Route { get; set; }
        public virtual Seat Seat { get; set; }
    }
}
